'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import { MuiThemeProvider, createTheme } from '@material-ui/core/styles';
import './globals.css';
import { CssBaseline, createTheme, ThemeProvider } from '@mui/material';
import NavBar from '@/Components/NavBar/NavBar';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

const theme = createTheme({
  palette: {
    primary: {
      main: '#262322',
    },
    secondary: {
      main: '#A71D31',
    },
  },
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider theme={theme}>
      <html lang='en'>
        <body
          className={inter.className}
          // style={{ backgroundColor: '#BFC3BA' }}
          // style={{ backgroundColor: '#dddad9' }}
          style={{ backgroundColor: '#f5f4f4' }}
        >
          <CssBaseline />
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
